#!/bin/sh
set -eu

PI_SUBAGENTS_VERSION="${PI_SUBAGENTS_VERSION:-0.19.0}"

mkdir -p "$HOME/.pi/agent"
cp -a --no-preserve=ownership /usr/local/share/pi-agent/. "$HOME/.pi/agent/"
pi install "npm:@tintinweb/pi-subagents@${PI_SUBAGENTS_VERSION}"
